name: PMManagerServers
author: matcracker
version: 1.1
api: [3.0.0-ALPHA6, 3.0.0-ALPHA7]
main: matcracker\PMManagerServers\Main

commands:
    pmms:
      description: Command of PM-ManagerServers

permissions:
    pmms.command.all:
      default: op
      description: Give all the permission of plugin
      children:
        pmms.command.start:
          default: op
          description: Give permission to start the executor
        pmms.command.stop:
          default: op
          description: Give permission to stop the executor
        pmms.command.queue:
          default: op
          description: Give permission to show list of commands to execute
        pmms.command.status:
          default: op
          description: Give permission to show the status of plugin
        pmms.command.debug:
          default: op
          description: Give permission to show and use debug command and messages
        pmms.command.reload:
          default: op
          description: Give permission to reload the config
        pmms.command.help:
          default: op
          description: Give permission to show help page
        pmms.command.info:
          default: op
          description: Give permission to show info about plugin